# Generated by Django 5.1.4 on 2024-12-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField()),
                ('shorturl', models.CharField(max_length=8)),
                ('hitcount', models.IntegerField(default=0)),
                ('hitcountperday', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
